apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-config
  namespace: monitoring
data:
  COLLECTOR_ZIPKIN_HOST_PORT: "9411"
  SPAN_STORAGE_TYPE: elasticsearch
  ES_SERVER_URLS: http://elasticsearch-service.elasticstack.svc.cluster.local:9200
  ES_USERNAME: elastic
  ES_VERSION: "7"
  ES_CREATE_INDEX_TEMPLATES: "false"
