apiVersion: v1
kind: ConfigMap
metadata:
  name: jaeger-config
  namespace: monitoring
data:
  COLLECTOR_ZIPKIN_HOST_PORT: "9411"
  SPAN_STORAGE_TYPE: elasticsearch
  ES_SERVER_URLS: http://elastic:12345678@elasticsearch-service.elasticstack.svc.cluster.local:9200
