apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jaeger
  namespace: monitoring
  labels:
    app: jaeger
spec:
  selector:
    matchLabels:
      app: jaeger
  serviceName: jaeger-service
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
        - name: jaeger
          image: jaegertracing/all-in-one:1
          ports:
            - containerPort: 5775
            - containerPort: 6831
            - containerPort: 6832
            - containerPort: 5778
            - containerPort: 16686
            - containerPort: 14250
            - containerPort: 14268
            - containerPort: 14269
            - containerPort: 9411
          envFrom:
            - configMapRef:
                name: jaeger-config
            - secretRef:
                name: jaeger-secret

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-service
  namespace: monitoring
spec:
  selector:
    app: jaeger
  type: NodePort
  ports:
    - name: agent-zipkin-compact
      protocol: UDP
      port: 5775
      targetPort: 5775
      nodePort: 30775
    - name: agent-jaeger-compact
      protocol: UDP
      port: 6831
      targetPort: 6831
      nodePort: 30831
    - name: agent-jaeger-binary
      protocol: UDP
      port: 6832
      targetPort: 6832
      nodePort: 30832
    - name: agent-serve-config
      protocol: TCP
      port: 5778
      targetPort: 5778
      nodePort: 30778
    - name: portal
      protocol: TCP
      port: 16686
      targetPort: 16686
      nodePort: 30686
    - name: grpc
      protocol: TCP
      port: 14250
      targetPort: 14250
      nodePort: 30250
    - name: collector-jaeger
      protocol: TCP
      port: 14268
      targetPort: 14268
      nodePort: 30268
    - name: http
      protocol: TCP
      port: 14269
      targetPort: 14269
      nodePort: 30269
    - name: collector-zipkin
      protocol: TCP
      port: 9411
      targetPort: 9411
      nodePort: 30411
