apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zipkin
  namespace: monitoring
  labels:
    app: zipkin
spec:
  selector:
    matchLabels:
      app: zipkin
  serviceName: zipkin-service
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
        - name: zipkin
          image: openzipkin/zipkin-slim:2
          ports:
            - containerPort: 9411
          envFrom:
            - configMapRef:
                name: zipkin-config
          readinessProbe:
            httpGet:
              path: /health
              port: 9411
            initialDelaySeconds: 10
            timeoutSeconds: 30
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /health
              port: 9411
            initialDelaySeconds: 20
            timeoutSeconds: 30
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1

---
apiVersion: v1
kind: Service
metadata:
  name: zipkin-service
  namespace: monitoring
spec:
  selector:
    app: zipkin
  type: NodePort
  ports:
    - name: collector
      protocol: TCP
      port: 9411
      targetPort: 9411
      nodePort: 30411
