kind: Namespace
apiVersion: v1
metadata:
  name: cron
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: cron
  name: replicaset-cleaner
rules:
  - apiGroups:
      - apps
    resources:
      - replicasets
      - statefulsets
    verbs:
      - delete
      - get
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: cron
  name: replicaset-cleaner
subjects:
  - kind: ServiceAccount
    namespace: cron
    name: replicaset-cleaner
roleRef:
  kind: Role
  name: replicaset-cleaner
  apiGroup: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: cron
  name: replicaset-cleaner
---
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: cron
  name: replicaset-cleaner
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: replicaset-cleaner
          containers:
            - name: kubectl
              image: bitnami/kubectl:latest
              command:
                - /bin/sh
                - -c
                - kubectl get rs -A -o wide | tail -n +2 | awk '{if ($3 + $4 + $5 == 0) print "kubectl delete rs -n "$1, $2 }' | sh
          restartPolicy: OnFailure
