apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-volume
  labels:
    type: local
spec:
  storageClassName: ""
  claimRef:
    name: postgres-claim
    namespace: database
  volumeMode: Filesystem
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteOnce
  local:
    path: /Volumes/Kubernetes/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim
  namespace: database
spec:
  storageClassName: ""
  volumeName: postgres-volume
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
