apiVersion: v1
kind: PersistentVolume
metadata:
  name: elasticsearch-vol
  labels:
    type: local
spec:
  storageClassName: ""
  claimRef:
    name: elasticsearch-pvc
    namespace: elasticstack
  volumeMode: Filesystem
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteOnce
  local:
    path: /usr/local/k8s/elasticsearch
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - docker-desktop
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc
  namespace: elasticstack
spec:
  storageClassName: ""
  volumeName: elasticsearch-vol
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
