apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-config
  namespace: elasticstack
data:
  ES_JAVA_OPTS: -Xms512m -Xmx1g
  bootstrap.memory_lock: "true"
  discovery.type: single-node
  xpack.security.transport.ssl.enabled: "false"
