apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: elasticstack
  labels:
    app: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
  serviceName: elasticsearch-service
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      volumes:
        - name: elasticsearch-storage
          persistentVolumeClaim:
            claimName: elasticsearch-claim
      containers:
        - name: elasticsearch
          image: docker.elastic.co/elasticsearch/elasticsearch:8.8.2
          ports:
            - containerPort: 9200
            - containerPort: 9300
          envFrom:
            - configMapRef:
                name: elasticsearch-config
            - secretRef:
                name: elasticsearch-secret
          readinessProbe:
            httpGet:
              path: /_cluster/health
              port: 9200
              httpHeaders:
                - name: Authorization
                  value: Basic ZWxhc3RpYzoxMjM0NTY3OA==
            initialDelaySeconds: 20
            timeoutSeconds: 30
            periodSeconds: 30
          livenessProbe:
            httpGet:
              path: /_cluster/health
              port: 9200
              httpHeaders:
                - name: Authorization
                  value: Basic ZWxhc3RpYzoxMjM0NTY3OA==
            initialDelaySeconds: 30
            timeoutSeconds: 30
            periodSeconds: 30
            failureThreshold: 3
            successThreshold: 1
          volumeMounts:
            - name: elasticsearch-storage
              mountPath: /usr/share/elasticsearch/data

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service
  namespace: elasticstack
spec:
  selector:
    app: elasticsearch
  type: NodePort
  ports:
    - name: client
      protocol: TCP
      port: 9200
      targetPort: 9200
      nodePort: 30200
