apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
  namespace: kafka
data:
  REPLICAS: "1"
  SERVICE: kafka-service
  NAMESPACE: kafka
  KAFKA_LOG_DIRS: /var/lib/kafka/data
  KAFKA_LOG_RETENTION_HOURS: "168"
  KAFKA_HEAP_OPTS: -Xms512m -Xmx512m
